using System.Collections;
using System.Collections.Generic;
using Normal.Realtime;
using Normal.Realtime.Serialization;
using UnityEngine;

namespace ViewR.Core.Networking.Normcore.SyncedActiveState
{
    [RealtimeModel(true)]
    public partial class BoolSyncModel
    {
        [RealtimeProperty(1, true, true)]
        private bool _syncedBool;
    }
}

/* ----- Begin Normal Autogenerated Code ----- */
namespace ViewR.Core.Networking.Normcore.SyncedActiveState {
    public partial class BoolSyncModel : RealtimeModel {
        public bool syncedBool {
            get {
                return _syncedBoolProperty.value;
            }
            set {
                if (_syncedBoolProperty.value == value) return;
                _syncedBoolProperty.value = value;
                InvalidateReliableLength();
                FireSyncedBoolDidChange(value);
            }
        }
        
        public delegate void PropertyChangedHandler<in T>(BoolSyncModel model, T value);
        public event PropertyChangedHandler<bool> syncedBoolDidChange;
        
        public enum PropertyID : uint {
            SyncedBool = 1,
        }
        
        #region Properties
        
        private ReliableProperty<bool> _syncedBoolProperty;
        
        #endregion
        
        public BoolSyncModel() : base(new MetaModel()) {
            _syncedBoolProperty = new ReliableProperty<bool>(1, _syncedBool);
        }
        
        protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
            _syncedBoolProperty.UnsubscribeCallback();
        }
        
        private void FireSyncedBoolDidChange(bool value) {
            try {
                syncedBoolDidChange?.Invoke(this, value);
            } catch (System.Exception exception) {
                UnityEngine.Debug.LogException(exception);
            }
        }
        
        protected override int WriteLength(StreamContext context) {
            var length = MetaModelWriteLength(context);
            length += _syncedBoolProperty.WriteLength(context);
            return length;
        }
        
        protected override void Write(WriteStream stream, StreamContext context) {
            WriteMetaModel(stream, context);
            
            var writes = false;
            writes |= _syncedBoolProperty.Write(stream, context);
            if (writes) InvalidateContextLength(context);
        }
        
        protected override void Read(ReadStream stream, StreamContext context) {
            var anyPropertiesChanged = false;
            while (stream.ReadNextPropertyID(out uint propertyID)) {
                var changed = false;
                switch (propertyID) {
                    case MetaModel.ReservedPropertyID: {
                        ReadMetaModel(stream, context);
                        break;
                    }
                    case (uint) PropertyID.SyncedBool: {
                        changed = _syncedBoolProperty.Read(stream, context);
                        if (changed) FireSyncedBoolDidChange(syncedBool);
                        break;
                    }
                    default: {
                        stream.SkipProperty();
                        break;
                    }
                }
                anyPropertiesChanged |= changed;
            }
            if (anyPropertiesChanged) {
                UpdateBackingFields();
            }
        }
        
        private void UpdateBackingFields() {
            _syncedBool = syncedBool;
        }
        
    }
}
/* ----- End Normal Autogenerated Code ----- */
