using Normal.Realtime;
using Normal.Realtime.Serialization;

namespace ViewR.Core.Experiences.ExperienceSync
{
    [RealtimeModel(true)]
    public partial class SyncExperienceModel
    {
        [RealtimeProperty(1, true, true)]
        private int _experienceID;
    }
}

/* ----- Begin Normal Autogenerated Code ----- */
namespace ViewR.Core.Experiences.ExperienceSync {
    public partial class SyncExperienceModel : RealtimeModel {
        public int experienceID {
            get {
                return _experienceIDProperty.value;
            }
            set {
                if (_experienceIDProperty.value == value) return;
                _experienceIDProperty.value = value;
                InvalidateReliableLength();
                FireExperienceIDDidChange(value);
            }
        }
        
        public delegate void PropertyChangedHandler<in T>(SyncExperienceModel model, T value);
        public event PropertyChangedHandler<int> experienceIDDidChange;
        
        public enum PropertyID : uint {
            ExperienceID = 1,
        }
        
        #region Properties
        
        private ReliableProperty<int> _experienceIDProperty;
        
        #endregion
        
        public SyncExperienceModel() : base(new MetaModel()) {
            _experienceIDProperty = new ReliableProperty<int>(1, _experienceID);
        }
        
        protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
            _experienceIDProperty.UnsubscribeCallback();
        }
        
        private void FireExperienceIDDidChange(int value) {
            try {
                experienceIDDidChange?.Invoke(this, value);
            } catch (System.Exception exception) {
                UnityEngine.Debug.LogException(exception);
            }
        }
        
        protected override int WriteLength(StreamContext context) {
            var length = MetaModelWriteLength(context);
            length += _experienceIDProperty.WriteLength(context);
            return length;
        }
        
        protected override void Write(WriteStream stream, StreamContext context) {
            WriteMetaModel(stream, context);
            
            var writes = false;
            writes |= _experienceIDProperty.Write(stream, context);
            if (writes) InvalidateContextLength(context);
        }
        
        protected override void Read(ReadStream stream, StreamContext context) {
            var anyPropertiesChanged = false;
            while (stream.ReadNextPropertyID(out uint propertyID)) {
                var changed = false;
                switch (propertyID) {
                    case MetaModel.ReservedPropertyID: {
                        ReadMetaModel(stream, context);
                        break;
                    }
                    case (uint) PropertyID.ExperienceID: {
                        changed = _experienceIDProperty.Read(stream, context);
                        if (changed) FireExperienceIDDidChange(experienceID);
                        break;
                    }
                    default: {
                        stream.SkipProperty();
                        break;
                    }
                }
                anyPropertiesChanged |= changed;
            }
            if (anyPropertiesChanged) {
                UpdateBackingFields();
            }
        }
        
        private void UpdateBackingFields() {
            _experienceID = experienceID;
        }
        
    }
}
/* ----- End Normal Autogenerated Code ----- */
